name: Portfolio CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'infra/**'

jobs:
  # JOB 1: Keamanan
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Trivy Vulnerability Scanner (IaC)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './infra'
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH'

  # JOB 2: Eksekusi Infrastruktur 
  deploy-to-local-cluster:
    needs: security-scan
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to K3d Kubernetes
        run: |
          # 1. Ubah file HTML menjadi ConfigMap agar bisa disuntikkan ke K8s
          kubectl create configmap portfolio-html-config --from-file=web/index.html -o yaml --dry-run=client | kubectl apply -f -
          
          # 2. Terapkan arsitektur K8s (Deployment & Service)
          kubectl apply -f k8s/
          
          # 3. Pantau status peluncuran
          kubectl rollout status deployment/portfolio-web