name: Portfolio CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'infra/**' # Sekarang pipeline akan mendeteksi perubahan pada Terraform

jobs:
  deploy-to-local-container:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Apply Infrastructure (Terraform)
        working-directory: ./infra
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Deploy Configuration (Ansible)
        working-directory: ./infra
        run: |
          ansible-playbook -i inventory.ini playbook.yml